// Copyright (c) 2020 Microsoft Corporation.
// Licensed under the MIT License.

// This file is autogenerated - do not commit manual changes.

#pragma once

#define UXTOOLSEXAMPLES_COMMIT_SHA "9a9ea48f7f46317ce66e83262a7696dba0b79cc6"
